setup controllers
chudisoft/Ruby-Blog pull request #6
Opened 2023-11-02 17:26 UTC by chudisoft

[Project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#project-requirements)

    Implement the design from the sneak peek wireframes.
        Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you will be using Devise in the coming milestone)

Note: Analyze the wireframes deeply and try to identify all the necessary elements and how a user would navigate from one page to another

![blog_root_users](https://github.com/chudisoft/Ruby-Blog/assets/11787384/1bd82b27-c5c9-4139-8a3f-f11ef64a9671)

![](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_all_posts.png)

Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
    Hint: In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).

2023-11-02 19:04 UTC, VICTOR-CHUKWU requested changes
Hi @chudisoft  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- [ ] some views look similar to design

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 19:04 UTC, VICTOR-CHUKWU commented on app/views/posts/index.html.erb
> +                    <label class=''>
- [ ] your post index page does not look like the given wireframe, kindly fix this views
your design :point_down: 
![Screenshot from 2023-11-02 19-56-40](https://github.com/chudisoft/Ruby-Blog/assets/66097371/d0a0e13d-4464-4c5e-beeb-d02f7c6e7936)

given design :point_down: 
![Screenshot from 2023-05-11 17-37-59](https://github.com/chudisoft/Ruby-Blog/assets/66097371/e4a0648d-fb20-4dd2-9b28-e28764f8c953)

2023-11-02 19:04 UTC, VICTOR-CHUKWU commented on app/views/posts/show.html.erb
> +<p>Text: <%= @post.text %></p>
- [ ] your post show does not look like give design, kindly fix the view
your design :point_down: 
![Screenshot from 2023-11-02 20-01-22](https://github.com/chudisoft/Ruby-Blog/assets/66097371/3478b3e0-4a28-4afb-8736-89678f69ac1f)
given design :point_down: 
![Screenshot from 2023-09-01 21-07-50](https://github.com/chudisoft/Ruby-Blog/assets/66097371/5a2753db-52e5-45e6-82aa-50922c40d52d)

2023-11-03 14:24 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @VICTOR-CHUKWU, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Application views setup correctly :white_check_mark: 
- [x] Application functions as expected :white_check_mark:  
- [x] Git flow is used  correctly :white_check_mark: 
- [x] Implemented all the required changes from the previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 15:29 UTC, merged